### PR TITLE
Use the host Python to handle the build

### PR DESCRIPTION
**Pull request by lazka**
This way building packages doesn't depend on msys2 packages

@eine

### CODE REVIEW

**Comment by lazka** [comment]
This would make it harder to run locally though. Should I make it depend on `os.environ.get('CI')`?

**Comment by eine** [comment]
It seems that this PR includes three features:

- Using the host Python instead of packages python and python-pip installed through pacman. I think this is an adequate change.
- Executing Python from Powershell instead of doing it from MSYS2's bash.
  - Calling `msys2.cmd` instead of bash, from Python.

The last point makes the pytest script non-portable. It will work in GHA only, because `msys2.cmd` is not expected to exist in any other environment. Hence, I think it would be desirable to call Python from MSYS2's bash, thus preversing the current `buildqueue.py`.

**Comment by lazka** [comment]
OK, so your goal is to make the build script work on GHA and on a local machine?

**Comment by eine** [comment]
@lazka, yes. For two purposes:

- Make it easier to debug problems with the script/logic.
- Allow to distribute the workload. The "local machine" might be another CI service, or the server/VPS of some maintainer. Similarly to other distributed systems, where multiple agents can "compete" to be the first in solving some issue (in this case, building a package). Anyway, ideally, if multiple machines are available, it would make sense to schedule the workload explicitly.

**Comment by lazka** [comment]
OK, sounds good, I'll keep that in mind.

**Pull request closed without merging**
